defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

permalink:           pretty

# Setup
title:               For Real Food
tagline:             Learn to grow real food. One step at a time.
baseurl:             https://rosscreighton.github.io/frf/

sass:
  sass_dir:          _scss
  style:            :compressed

